### PR TITLE
Release version 2.0.0

### PR DESCRIPTION
**Pull request by abergs**
This PR bumps the version to 2.0.0.

The reason for the major version is because the large number of changes, some that in theory could be breaking.

Preview releases are up on NuGet: https://www.nuget.org/packages/Fido2/2.0.0-preview2

Release notes: 
## 💥 Breaking change

- Improved API consistency for response parsing @Cooke (#150)
- Core 3.0 Support @abergs (#145)
- MDS refactoring @mackie1001 (#125)
- Moved Models and Public classes to Fido2NetLib.Models project @abergs (#103)

## 🚀 Features and enhancements

- Make TPM attestation format verifier work more like packed with regard to X5C @aseigler (#180)
- Switch remaining manual ASN.1 decoding to using the AsnElt library @aseigler (#176)
- Switch to using NSec.Cryptography v20.2.0 for Ed25519 @aseigler (#169)
- Upgrade PeterO.Cbor package to v4.1.2 @aseigler (#168)
- Add code coverage and codecov reporting @abergs (#170)
- Fix SafetyNet attestation verification, add unit tests @aseigler (#165)
- Add optional validation of attestation root certs @AdamUCF (#164)
- Add many unit tests for nearly all attestation types @aseigler (#162)
- adding solo tap and somu metadata to static metadata repository @AdamUCF (#157)
- Fix for issue #153 - System.IdentityModel.Tokens.Jwt version upgrade an associated fixes @mackie1001 (#156)
- Fixed challenge replay attack issue in examples @Cooke (#151)
- Improved API consistency for response parsing @Cooke (#150)
- Core 3.0 Support @abergs (#145)
- Add MDS configuration to Fido2Configuration @damienbod (#134)
- Remove CNG dependencies to allow cross platform scenarios @aseigler (#132)
- Code cleanup @Shtong (#127)
- MDS refactoring @mackie1001 (#125)
- Moved Models and Public classes to Fido2NetLib.Models project @abergs (#103)
- Refactor AuthenticatorData, and subcomponents @aseigler (#104)
- Redesign @abergs (#102)
- Continue redesign of AuthenticatorData, AttestedCredentialData, and CredentialPublicKey @aseigler (#100)
- Begin redesign of AuthenticatorData, AttestedCredentialData, and Cred… @aseigler (#97)
- Restructure repository per proposal in #79 @aseigler (#95)
- Convert metadata to async @aseigler (#83)
- Refactor and improve ToEnum extension method @CodeTherapist (#85)
- Add minimal tests for Base64Url class @CodeTherapist (#84)
- Parsing EnumMember values to Enum @daviddesmet (#75)
- Support Target Frameworks by OS @daviddesmet (#74)
- Properties of PublicKeyCredentialType enum are nullable @daviddesmet (#73)
- Prefer enumeration @daviddesmet (#69)
- Removed net462 from test project @abergs (#65)
- Added a guarding mechanism to prevent usage in .NET46X @MeikTranel (#66)
- TPM chain validation, move MDS to packed attestation specific area @aseigler (#63)
- Please review @aseigler (#59)

## 🐛 Bug Fixes

- Fix SafetyNet attestation verification, add unit tests @aseigler (#165)
- Fix for issue #153 - System.IdentityModel.Tokens.Jwt version upgrade an associated fixes @mackie1001 (#156)
- Bug fix: require_resident_key @Shane32 (#152)
- EdDSA test, sign the actual data, not a hash of the data @aseigler (#128)
- Problem with non English OS @fa18swiss (#119)
- corrected error variable @Celdus (#118)
- Wrong naming of attestationObject and clientDataJSON in usernameless.… @Wesseldr (#105)
- Add field userHandle in verifyAssertionWithServer @Wesseldr (#108)
- use AppId instead of RpId to hash when AppId-Extensions-Flag is set @dgorbach (#99)
- Fixes enum parsing with dashed values @daviddesmet (#90)

## 🧰 Maintenance & documentation

- Solve CI/CD Missing packages error @abergs (#182)
- Improved release note template @abergs (#174)
- Require labels on PR for better release notes @abergs (#173)
- Added better badges @abergs (#172)
- Added support for release-drafter as GH action @abergs (#171)
- fix 404 CHANGELOG link  @damienbod (#163)
- Adding a changelog, and 2 links to the readme @damienbod (#160)
- Created CONTRIBUTING.md @Shtong (#129)
- Cleaned dead code @Shtong (#131)
- Adds xml comment documentation @CodeTherapist (#122)
- Code cleanup @Shtong (#127)
- Activating Open Collective @monkeywithacupcake (#123)
- Fix minor typos in demo javascript @Tornhoof (#115)
- fix links in readme to demo controllers @damienbod (#114)
- Redesign @abergs (#102)
- Add webauthn.io site to Read More @nicksteele (#81)
- Update README.md @aseigler (#77)
- Added syntax highlight to the code samples @herrjemand (#67)
- General project structure overhaul @MeikTranel (#61)

### CODE REVIEW

**Comment by aseigler** [comment]
> @aseigler We are waiting for #166, right?

Yes please, hoping to have it resolved in the next couple of days.

**Comment by abergs** [comment]
@aseigler No stress, preview package is out for consumers who need it.

**Comment by mackie1001** [comment]
Thanks guys :)

**Comment by aseigler** [comment]
image

**Comment by abergs** [comment]
Published preview2 package: https://www.nuget.org/packages/Fido2/2.0.0-preview2

@mackie1001 Could you try and verify that preview works for you?

**Comment by aseigler** [comment]
> Published preview2 package: https://www.nuget.org/packages/Fido2/2.0.0-preview2
> 
> @mackie1001 Could you try and verify that preview works for you?

Bump.

**Comment by abergs** [comment]
@mackie1001 How has your experience been with the 2.0 preview?

**Comment by mackie1001** [comment]
@abergs Apologies for the lack of response. I've not had the chance to pick it up as I've been focusing on another project at work. I will try and give it a go over the weekend.

**Comment by mackie1001** [comment]
@abergs Overall it seems fine, however I have encountered an issue when trying to register my Windows Hello enabled laptop. 

The exception when calling `MakeNewCredentialAsync()` is:

```
Asn1.AsnException: wrong number of sub-elements: 3 (expected: 1)
   at Asn1.AsnElt.CheckNumSub(Int32 n)
   at Fido2NetLib.AttestationFormat.Tpm.SANFromAttnCertExts(X509ExtensionCollection exts)
   at Fido2NetLib.AttestationFormat.Tpm.Verify()
   at Fido2NetLib.AuthenticatorAttestationResponse.<VerifyAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Fido2NetLib.Fido2.<MakeNewCredentialAsync>d__6.MoveNext()
```
It looks like the TPM logic has been beefed up considerably since 1.1.

The error occurs on line 279 of Tpm.cs:

```
exp.CheckNumSub(1);
```

I've reproduced it with the following settings in the custom registration in the demo app:

Attestation type: Direct
Autheticator: Platform (TPM)
User verification: discouraged

The authenticator is "Windows Hello Hardware Authenticator", AAGUID: 08987058-cadc-4b81-b6e1-30de50dcbe96

Playing around a bit I managed to tweak the code in line with the sample on page 35 of this doc: https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf

```
// SEQUENCE
30 49
    // SET
    31 16
        // SEQUENCE
        30 14
            // OBJECT IDENTIFER tcg-at-tpmManufacturer (2.23.133.2.1)
            06 05 67 81 05 02 01
            // UTF8 STRING id:54434700 (TCG)
            0C 0B 69 64 3A 35 34 34 33 34 37 30 30
    // SET
    31 17
        // SEQUENCE
        30 15
            // OBJECT IDENTIFER tcg-at-tpmModel (2.23.133.2.2)
            06 05 67 81 05 02 02
            // UTF8 STRING ABCDEF123456
            0C 0C 41 42 43 44 45 46 31 32 33 34 35 36
    // SET
    31 16
        // SEQUENCE
        30 14
            // OBJECT IDENTIFER tcg-at-tpmVersion (2.23.133.2.3)
            06 05 67 81 05 02 03
            // UTF8 STRING id:00010023
            0C 0B 69 64 3A 30 30 30 31 30 30 32 33 
```

`var exp = generalName.GetSub(0);` actually ends up being the top level `// SEQUENCE` from that sample and not the level above like the current code assumes. 

I think the mistake was thinking the `GeneralName` to `directoryName` relationship was "has a" rather than "is a".

I'll raise a PR ASAP but I'd appreciate some help verifying the fix using another real world TPM implenentation - e.g. OSX maybe?

**Comment by aseigler** [comment]
There is no other real world TPM implementation right now, only Windows 10. Apple doesn't TPM, the only real hope for TPM would be Linux someday if someone wants it bad enough.

**Comment by mackie1001** [comment]
@aseigler I assumed all TPM-based implementations used `tpm` but it looks like I was wrong. Windows Hello Software Authenticator uses `packed` too.

**Comment by aseigler** [comment]
> @aseigler I assumed all TPM-based implementations used `tpm` but it looks like I was wrong. Windows Hello Software Authenticator uses `packed` too. 
> 

Yes, a platform authenticator attestation request on Windows 10 can result in packed or TPM depending on several factors.

**Comment by mackie1001** [comment]
FYI I've now tested this on Windows 10 1909 and 2004 and get the same result.

**Comment by herrjemand** [comment]
Congrats guys!

**Pull request merged**
