### PR TITLE
Please review

### LINKED ISSUE #7: [Security] Remove dependency on PeterO.Cbor package
Decrease dependency count by removing the dependency on PeterO.Cbor and instead copy the CBOR decode implementation.

Disadvantage: No automatic updates in case of bugs in implmentation
Advantage: No package poisoning.

### PR DESCRIPTION
**Pull request by aseigler**
- Added PeterO.Cbor as local project to close #7
- Added Chaos.NaCl as local project for EdDSA support
- Added Yubico root and known aaguid to custom metadata to support trust path verification for at least some Yubico devices

### CODE REVIEW

**Comment by abergs** [comment]
Will hopefully be able to review tomorrow. Github says it has conflicts but not sure if that's a false alarm?

**Comment by aseigler** [comment]
I haven't seen any conflicts?

**Comment by abergs** [comment]
This is the Github UI, but I can try to do it manually.

Do have any more commits or are you good to go?

image

**Comment by aseigler** [comment]
That's bizarre...this is what I see. 


I don't have anything else right at the moment, I was mainly concerned about adding the CBOR and Chaos.NaCl projects. It works fine for me, just wanted to make sure it works for you and that it was done properly.

**Comment by abergs** [comment]
I think that is because I run the rebase and merge mode.
I will take a look at it and test locally 👍

**Pull request merged**
