### PR TITLE
Upgrade PeterO.Cbor package to v4.1.2

### PR DESCRIPTION
**Pull request by aseigler**
...and switch to using it as a PackageReference.  This makes more sense to me than continuing the way this has been configured, but I'm open to comments and suggestions.

### CODE REVIEW

**Comment by abergs** [comment]
The reason why it's not a PackageReference: https://github.com/abergs/fido2-net-lib/issues/7

Isn't the concern still valid?

**Comment by aseigler** [comment]
The concern hasn't changed, I am just not completely convinced the concern was ever valid to begin with, and wanted to bring it back up for discussion since many more eyes are on this now. The project has other package references, including those where upgrades have broken stuff, like #153. Seems like using a package reference would make it easier to keep dependencies up to date, see #167. It just feels odd to have a robust package management system and then completely circumvent it in the manner we have, that's why I wanted to bring it back up.

**Comment by abergs** [comment]
I hear you, maybe it's over-the-top.

**Comment by aseigler** [comment]
Merging based on https://twitter.com/blowdart/status/1266020693558169600.

**Pull request merged**
