### PR TITLE
Adds xml comment documentation

### PR DESCRIPTION
**Pull request by CodeTherapist**

### CODE REVIEW

**Comment by CodeTherapist** [comment]
@aseigler: Let me know, whether this goes in the right direction - then I would continue. Any help or suggestions would be appreciated.

Closes #122

**Comment by aseigler** [comment]
> @aseigler: Let me know, whether this goes in the right direction - then I would continue. Any help or suggestions would be appreciated.
> Closes #121

Love it!

**Comment by abergs** [comment]
@CodeTherapist I like this. Are you finishing up any changes or should we go ahead and mark this as ready and add more documentation iteratively?

**Comment by CodeTherapist** [comment]
@abergs I will finish this up - PR will be ready today or tomorrow.

**Comment by CodeTherapist** [comment]
I noticed the following things, while documenting:

* Coulnd't find the following enum values from the AuthenticatorStatus: [FIDO_CERTIFIED_L1plus](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/AuthenticatorStatus.cs#L56), [FIDO_CERTIFIED_L2plus](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/AuthenticatorStatus.cs#L61) and [FIDO_CERTIFIED_L3plus](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/AuthenticatorStatus.cs#L66)

* Couldn't find the [BiometricStatusReport](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/BiometricStatusReport.cs#L5).

* Members of [BiometricAccuracyDescriptor](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/BiometricAccuracyDescriptor.cs#L14) didn't match with our code.

* Couldn't find any information of the [MetadataStatement.Hash](https://github.com/abergs/fido2-net-lib/blob/5372d3036cf56ae7b930f4ee2c527f789749ba39/Src/Fido2.Models/MetadataStatements/MetadataStatement.cs#L191) property.

I would like to be complete and thoroughly as possible. Let me know what I should do with the above mentioned types, properties etec. Any help is as always appreciated.

**Comment by aseigler** [comment]
Most of the things you could not find are in:
https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.pdf

The MetadataStatement.Hash is what is described here: https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html#metadata-toc-object-processing-rules, step 6, sub-step 4. It is the computed hash value of the metadata statement that we compare to what we found in the TOC.  It is likely that this will be refactored out at some point, this was really included just to get the service functional and passing the conformance tests.

Thanks for your help!

**Comment by CodeTherapist** [comment]
@aseigler Thanks for the help. I was using that document too - looks like I didn't catched everything.
Even when it's likely to be refactored, as long as it's there I will document it. I could add under remarks that this will maybe moved away. Later versions could mark the property as obsolete etc.

I will finish this and resolve the conflicts.

**Comment by aseigler** [comment]
Thank you!

**Pull request merged**
