### PR TITLE
Error handling + client JavaScript improvements

### PR DESCRIPTION
**Pull request by ondrokrc**
- Exception handling in Controller.cs (the diff for Controller.cs is weird, I just added try catch blocks to the methods)
- Created base class Fido2ResponseBase for error handling
- Handling returned errors in client JavaScript
- client JavaScript cleanup - moved successful swal() dialogs to proper place
- client JavaScript unification - similar workflow for all the fetch() calls

### CODE REVIEW

**Comment by abergs** [comment]
Looks good but could you rest the controller.cs file so that we don't end up with that huge diff?

**Comment by ondrokrc** [comment]
Sure, but I'm having trouble with it at the moment. Maybe I'll have to start over and fork again.

**Comment by abergs** [comment]
@ondrokrc Yes. The commit history is long in this PR. You should probably copy your local changes and reset your master to abergs/master. (It's the same as checking out/forking again)

**Comment by ondrokrc** [comment]
I did the reset and applied the changes freshly again.

**Comment by abergs** [comment]
Looks good!

**Comment by aseigler** [comment]
Has https://fido2.azurewebsites.net been updated with the latest code?

**Comment by abergs** [comment]
Published it now! 👍 
(It ran quite old code before the publish today)

**Pull request merged**
